# Generated by Django 3.2.25 on 2024-05-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('item', models.CharField(max_length=50)),
                ('shop', models.CharField(max_length=500)),
                ('doc', models.CharField(max_length=500)),
                ('dates', models.CharField(max_length=20)),
            ],
        ),
    ]
